### PR TITLE
Fix edit command to preserve archived view

### LINKED ISSUE #155: Update edit command to display archived view after editing archived opportunity

### PR DESCRIPTION
**Pull request by Kevin-129**
Fixes #155

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -86,8 +86,16 @@ public CommandResult execute(Model model) throws CommandException {
...
+        boolean wasArchived = opportunityToEdit.isArchived();
+
         model.setOpportunity(opportunityToEdit, editedOpportunity);
-        model.updateFilteredOpportunityList(PREDICATE_SHOW_UNARCHIVED_OPPORTUNITIES);
+
+        if (wasArchived) {
+            model.updateFilteredOpportunityList(PREDICATE_SHOW_ARCHIVED_OPPORTUNITIES);
+        } else {
+            model.updateFilteredOpportunityList(PREDICATE_SHOW_UNARCHIVED_OPPORTUNITIES);
+        }
```
Comment (seanchiew) [inline src/main/java/seedu/address/logic/commands/EditCommand.java]: Could we add a regression test for this new archived-view path in `EditCommandTest`? Right now this PR changes the post-edit filtering behavior, but I don’t see a test that first puts the model into archived view, edits an archived opportunity, and asserts the filtered list stays archived.

**Review by shermszz — COMMENTED** [review]
LGTM
